"""Write ../fig-data.js, the traces drawn on the analysis page.

    python make_figures.py
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from sim import Circuit, dc, transient, press, rest

DT = 2e-4


def trace(t_on, t_off, t_end, every, **kw):
    c = Circuit(**kw)
    V = rest(c)
    out, _ = transient(c, press(t_on, t_off), t_end, DT, V0=V, record=['Vm'])
    pts = [(0.0, round(c.v(V, 'Vm'), 3))] + [(round(t, 4), round(d['Vm'], 3)) for t, d, _ in out]
    return pts[::every]


fig = {'press': [0.005, 0.405], 'panels': [], 'zoom': {'press': [0.001, 0.35], 'series': []}}
for key, title, kw in [
    ('ok', '全部接好（應該看到的）', dict(rpot=0.0)),
    ('so', 'Slow out 沒接上（測試 9、10d）', dict(rpot=0.0, so_vm=False)),
    ('both', 'FI 沒有 V+，Slow out 也沒接上（測試 1）', dict(rpot=0.0, fi_vplus=False, so_vm=False)),
    ('none', '只有 Stimulator + Leak（測試 10b）', dict(rpot=0.0, fi=False, so=False)),
]:
    fig['panels'].append({'key': key, 'title': title, 'pts': trace(0.005, 0.405, 0.9, 10, **kw)})
    print('panel', key, 'done')

for key, name, kw in [
    ('built', 'PCB 實際值（R13 100 kΩ）', dict(rpot=0.0)),
    ('ttx', '拔掉 Fast inward', dict(rpot=0.0, fi=False)),
    ('sch', '電路圖數值（9 V、1 kΩ、Qsense 在 SW 後）', dict(rpot=0.0, vplus=9.0, r13=1e3, qsense_on_switched=True)),
]:
    pts = trace(0.001, 0.351, 0.12, 2, **kw)
    fig['zoom']['series'].append({'key': key, 'name': name, 'pts': pts})
    print('zoom', key, 'done')

path = os.path.join(HERE, '..', 'fig-data.js')
with open(path, 'w', encoding='utf-8') as f:
    f.write('/* generated by sim/make_figures.py */\nwindow.FIG = ')
    json.dump(fig, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print('wrote', os.path.normpath(path))
